### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by ansoni-san** [saltosystems/winrt-go#72]
Currently running into this issue:

```
fatal error: concurrent map writes

goroutine 2077 [running]:
runtime.throw({0xfa2437?, 0xea97b7?})
        C:/Program Files/Go/src/runtime/panic.go:992 +0x76 fp=0xc0001c5c38 sp=0xc0001c5c08 pc=0xdf6396
runtime.mapassign_fast64ptr(0xf7bbe0, 0xc00011a990, 0x1baf7919670)
        C:/Program Files/Go/src/runtime/map_fast64.go:267 +0x2cb fp=0xc0001c5c70 sp=0xc0001c5c38 pc=0xdd260b
github.com/saltosystems/winrt-go/windows/foundation.NewAsyncOperationCompletedHandler(0xc000262410, 0xc000109cf8)
        winrt-go/windows/foundation/asyncoperationcompletedhandler.go:69 +0xa6 fp=0xc0001c5ca0 sp=0xc0001c5c70 pc=0xea99a6
tinygo.org/x/bluetooth.awaitAsyncOperation(0x1baf7b356e0?, {0xfad272, 0x52})
        go-bluetooth/adapter_windows.go:43 +0x10b fp=0xc0001c5d28 sp=0xc0001c5ca0 pc=0xeaf62b
tinygo.org/x/bluetooth.DeviceCharacteristic.write({{0xcd8fedc, 0x8333aa3c, 0xa91449a4, 0x78667579}, 0x1baf7b356e0, 0x4, 0xc0004fc140}, {0xc000981810, 0xc, 0x10}, ...)
        go-bluetooth/gattc_windows.go:296 +0x133 fp=0xc0001c5da8 sp=0xc0001c5d28 pc=0xeb17f3
tinygo.org/x/bluetooth.DeviceCharacteristic.WriteWithoutResponse({{0xcd8fedc, 0x8333aa3c, 0xa91449a4, 0x78667579}, 0x1baf7b356e0, 0x4, 0xc0004fc140}, {0xc000981810?, 0xc00071b6b0?, 0xc0001c5e90?})
        go-bluetooth/gattc_windows.go:272 +0x68 fp=0xc0001c5e00 sp=0xc0001c5da8 pc=0xeb1688
main.(*Characteristic).Write(0xc0001240e0?, {0xc000981810?, 0x62?, 0x4?})
        generic_driver.go:43 +0xc7 fp=0xc0001c5ea0 sp=0xc0001c5e00 pc=0xf202e7
main.(*GenericDriver).SendCommand(0xc0001240e0, {0xf9d982, 0x7}, {0xc000981810, 0xc, 0x10})
        generic_driver.go:274 +0x2ba fp=0xc0001c5f68 sp=0xc0001c5ea0 pc=0xf2185a
main.NewGenericDriver.func1({0xf9d982?, 0x0?}, {0xc000981810?, 0x0?, 0x0?})
        generic_driver.go:81 +0x39 fp=0xc0001c5fa8 sp=0xc0001c5f68 pc=0xf20839
main.(*DeviceInstructionExecutor).Run.func1.2()
        generic_driver.go:731 +0x3b fp=0xc0001c5fe0 sp=0xc0001c5fa8 pc=0xf237fb

goroutine 2091 [runnable]:
tinygo.org/x/bluetooth.awaitAsyncOperation(0x1baf7b296f0?, {0xfad272, 0x52})
        go-bluetooth/adapter_windows.go:48 +0x125
tinygo.org/x/bluetooth.DeviceCharacteristic.write({{0xcd8fedc, 0x8333aa3c, 0xa91449a4, 0x78667579}, 0x1baf7b296f0, 0x4, 0xc0004fc0e0}, {0xc0009814b0, 0xc, 0x10}, ...)
        go-bluetooth/gattc_windows.go:296 +0x133
tinygo.org/x/bluetooth.DeviceCharacteristic.WriteWithoutResponse({{0xcd8fedc, 0x8333aa3c, 0xa91449a4, 0x78667579}, 0x1baf7b296f0, 0x4, 0xc0004fc0e0}, {0xc0009814b0?, 0xc00020e930?, 0xc00036be90?})
        go-bluetooth/gattc_windows.go:272 +0x68
main.(*Characteristic).Write(0xc000124000?, {0xc0009814b0?, 0x62?, 0x4?})
        generic_driver.go:43 +0xc7
main.(*GenericDriver).SendCommand(0xc000124000, {0xf9d982, 0x7}, {0xc0009814b0, 0xc, 0x10})
        generic_driver.go:274 +0x2ba
main.NewGenericDriver.func1({0xf9d982?, 0xc00036bfd0?}, {0xc0009814b0?, 0xc0000961b0?, 0x1?})
        generic_driver.go:81 +0x39
created by main.(*DeviceInstructionExecutor).Run.func1
        generic_driver.go:731 +0x41d
```

By sending many commands at 100ms intervals to multiple devices at once.

Seems fairly straight forward when looking at `asyncoperationcompletedhandler.go`:
```golang

var callbacksAsyncOperationCompletedHandler map[unsafe.Pointer]AsyncOperationCompletedHandlerCallback = make(map[unsafe.Pointer]AsyncOperationCompletedHandlerCallback)

func NewAsyncOperationCompletedHandler(iid *ole.GUID, callback AsyncOperationCompletedHandlerCallback) *AsyncOperationCompletedHandler {
	inst := (*AsyncOperationCompletedHandler)(C.malloc(C.size_t(unsafe.Sizeof(AsyncOperationCompletedHandler{}))))
	inst.RawVTable = (*interface{})((unsafe.Pointer)(C.winrt_getAsyncOperationCompletedHandlerVtbl()))
	inst.IID = *iid // copy contents

	callbacksAsyncOperationCompletedHandler[unsafe.Pointer(inst)] = callback

	inst.addRef()
	return inst
}
```

The map assignment just needs a Mutex.

Although, this and #71 may indicate that some other slight re-organisation may be useful. I don't know if you'll want to bundle that into a single change that will avoid both.

**Comment by jagobagascon** [comment]
Thanks for the report! I was able to reproduce the issue with the following snippet:

```go
func main() {
	g := ole.NewGUID(foundation.GUIDIAsyncOperation)
	for i := 0; i < 100; i++ {
		go func() {
			a := foundation.NewAsyncOperationCompletedHandler(g, func(instance *foundation.AsyncOperationCompletedHandler, asyncInfo *foundation.IAsyncOperation, asyncStatus foundation.AsyncStatus) {
			})
			a.Release()
		}()
	}
}
```

I'm still not sure about #71, so I'll work on a fix for this, and do some refactor in a later commit if required.
