### ISSUE TITLE
fatal error: sync: inconsistent mutex state

### ISSUE THREAD

**Issue by 5k3105** [saltosystems/winrt-go#77]
The specific line in my code is using `.Read()` on a BLE device characteristic every two seconds.
After about the tenth read, it will fail: `fatal error: sync: inconsistent mutex state`
But this same error has also happened in other calls, like `device.DiscoverServices(nil)`

I am cross compiling from linux like this: `GOOS=windows CC=x86_64-w64-mingw32-gcc go build`

Thanks for all your great work - this is the only way to use ble from go on windows. Pretty amazing!

```
fatal error: sync: inconsistent mutex state

goroutine 1 [running]:
runtime.throw({0x7ff6cd1f1f80?, 0xf318483f7790?})
        /usr/lib/go/src/runtime/panic.go:1077 +0x65 fp=0xc00005fb00 sp=0xc00005fad0 pc=0x7ff6cd135f05
sync.throw({0x7ff6cd1f1f80?, 0x1?})
        /usr/lib/go/src/runtime/panic.go:1056 +0x18 fp=0xc00005fb20 sp=0xc00005fb00 pc=0x7ff6cd15da98
sync.(*Mutex).lockSlow(0x2c29685c5f8)
        /usr/lib/go/src/sync/mutex.go:180 +0x245 fp=0xc00005fb70 sp=0xc00005fb20 pc=0x7ff6cd1691a5
sync.(*Mutex).Lock(...)
        /usr/lib/go/src/sync/mutex.go:90
github.com/saltosystems/winrt-go/windows/foundation.(*AsyncOperationCompletedHandler).addRef(0x7ff6cd1d6780?)
        /home/asd/go/pkg/mod/github.com/saltosystems/winrt-go@v0.0.0-20230510070731-e096b9afa761/windows/foundation/asyncoperationcompletedhandler.go:76 +0x56 fp=0xc00005fbc0 sp=0xc00005fb70 pc=0x7ff6cd19e616
github.com/saltosystems/winrt-go/windows/foundation.NewAsyncOperationCompletedHandler(0xc0000b4040, 0xc0000a80a8)
        /home/asd/go/pkg/mod/github.com/saltosystems/winrt-go@v0.0.0-20230510070731-e096b9afa761/windows/foundation/asyncoperationcompletedhandler.go:70 +0xd8 fp=0xc00005fbf0 sp=0xc00005fbc0 pc=0x7ff6cd19e578
tinygo.org/x/bluetooth.awaitAsyncOperation(0x2c2966c5de0?, {0x7ff6cd1f6d17, 0x6b})
        /home/asd/go/pkg/mod/tinygo.org/x/bluetooth@v0.7.0/adapter_windows.go:43 +0x105 fp=0xc00005fc78 sp=0xc00005fbf0 pc=0x7ff6cd1a36a5
tinygo.org/x/bluetooth.(*DeviceCharacteristic).Read(0x77359400?, {0xc00005fd71, 0xff, 0xff?})
        /home/asd/go/pkg/mod/tinygo.org/x/bluetooth@v0.7.0/gattc_windows.go:328 +0x5f fp=0xc00005fcc0 sp=0xc00005fc78 pc=0x7ff6cd1a521f
main.main()
        /my_code/main.go:65 +0x3f1 
        ***/ n, err := device_characteristic.Read(buf) /***
        fp=0xc00005ff40 sp=0xc00005fcc0 pc=0x7ff6cd1ab1b1
runtime.main()
        /usr/lib/go/src/runtime/proc.go:267 +0x2b2 fp=0xc00005ffe0 sp=0xc00005ff40 pc=0x7ff6cd138892
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x7ff6cd1625a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000039fa8 sp=0xc000039f88 pc=0x7ff6cd138cae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.forcegchelper()
        /usr/lib/go/src/runtime/proc.go:322 +0xb8 fp=0xc000039fe0 sp=0xc000039fa8 pc=0x7ff6cd138b38
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x7ff6cd1625a1
created by runtime.init.6 in goroutine 1
        /usr/lib/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00003bf78 sp=0xc00003bf58 pc=0x7ff6cd138cae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /usr/lib/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc00003bfc8 sp=0xc00003bf78 pc=0x7ff6cd123b74
runtime.gcenable.func1()
        /usr/lib/go/src/runtime/mgc.go:200 +0x25 fp=0xc00003bfe0 sp=0xc00003bfc8 pc=0x7ff6cd118ec5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0x7ff6cd1625a1
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000160e0?, 0x7ff6cd210aa8?, 0x1?, 0x0?, 0xc000036b60?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000049f70 sp=0xc000049f50 pc=0x7ff6cd138cae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x7ff6cd29aa00)
        /usr/lib/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000049fa0 sp=0xc000049f70 pc=0x7ff6cd121409
runtime.bgscavenge(0x0?)
        /usr/lib/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000049fc8 sp=0xc000049fa0 pc=0x7ff6cd12199c
runtime.gcenable.func2()
        /usr/lib/go/src/runtime/mgc.go:201 +0x25 fp=0xc000049fe0 sp=0xc000049fc8 pc=0x7ff6cd118e65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x7ff6cd1625a1
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x7ff6cd1e9e40?, 0x1cd139c01?, 0x0?, 0x0?, 0x7ff6cd141025?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00003de28 sp=0xc00003de08 pc=0x7ff6cd138cae
runtime.runfinq()
        /usr/lib/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00003dfe0 sp=0xc00003de28 pc=0x7ff6cd117f87
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00003dfe8 sp=0xc00003dfe0 pc=0x7ff6cd1625a1
created by runtime.createfing in goroutine 1
        /usr/lib/go/src/runtime/mfinal.go:163 +0x3d
```

**Comment by ansoni-san** [comment]
Try updating 🙂. This has already been resolved.

If you're using https://github.com/tinygo-org/bluetooth please switch to its dev branch, as the release branch lags quite far behind.

_They are sometimes matching releases to TinyGo itself, which has slower release cycles than a library would want._

**Comment by glerchundi** [comment]
Thanks for the issue @5k3105 and for the cross-referencing @ansoni-san. Yes, it seems to be the same issue which have been reported in https://github.com/saltosystems/winrt-go/issues/71, resolved in https://github.com/saltosystems/winrt-go/pull/74 and bumped in tinygo-org/bluetooth#173.

Closing then, reopen if it's still happening.

**Comment by 5k3105** [comment]
Working nicely after `go get tinygo.org/x/bluetooth@dev`

Thanks guys!
